version: '3'
services:
  # Global services
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: global_nginx_proxy
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    privileged: true
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 64M
        limits:
          memory: 256M
    environment:
      - HTTPS_METHOD=noredirect
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "8080" # Only for stub_status
    depends_on:
      - bdic3025j-des-cipher
      - instrument_shop
      - bdic3023j-software-methodology-q-a-platform
      - comp3019j-web-application-development-grocery-list-website
      - fyp_offer_master_nginx
      - oauth_center_application_prod
      - oauth_center_application_demo
      - jupyter_notebook_reader
    networks:
      - offer_master_network
      - instrument_shop_network
      - oath_center_network
      - comp3019j_network
      - bdic3023j_network
      - bdic3025j_network
      - jupyter_notebook_reader_network
      - maintenance_network
      - grafana_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=me@yuyangwang.org
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    restart: always

  oauth_center_application_prod:
    image: echocool/oauth_center_django:latest
    container_name: oauth_center_application_prod
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          memory: 256M
    environment:
      - DEBUG=False
      - VIRTUAL_HOST=oauth.yuyangwang.org,auth.yuyangwang.org
      - LETSENCRYPT_HOST=oauth.yuyangwang.org,auth.yuyangwang.org
      - VIRTUAL_PORT=8080
    expose:
      - "8080"
    networks:
      - oath_center_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/test/health/" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure

  jupyter_notebook_reader:
    image: echocool/jupyter_notebook_reader:${VERSION:-latest}
    container_name: jupyter_notebook_reader
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - VIRTUAL_HOST=jupyter.demo.yuyangwang.org,jupyter-reader.demo.yuyangwang.org
      - LETSENCRYPT_HOST=jupyter.demo.yuyangwang.org,jupyter-reader.demo.yuyangwang.org
      - VIRTUAL_PORT=5000
    networks:
      - jupyter_notebook_reader_network
    expose:
      - "5000"
    restart: on-failure

  oauth_center_application_demo:
    image: echocool/oauth_center_django:latest
    container_name: oauth_center_django_demo
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - DEBUG=False
      - VIRTUAL_HOST=oauth.demo.yuyangwang.org,auth.demo.yuyangwang.org
      - LETSENCRYPT_HOST=oauth.demo.yuyangwang.org,auth.demo.yuyangwang.org
      - VIRTUAL_PORT=8080
    expose:
      - "8080"
    networks:
      - oath_center_network
    restart: on-failure

  bdic3025j-des-cipher:
    image: echocool/bdic3025j-security-privacy-des-algorithm-cipher:${VERSION:-latest}
    container_name: bdic3025j-security-privacy-des-algorithm-cipher
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - VIRTUAL_HOST=bdic3025j.demo.yuyangwang.org,des.demo.yuyangwang.org
      - LETSENCRYPT_HOST=bdic3025j.demo.yuyangwang.org,des.demo.yuyangwang.org
      - VIRTUAL_PORT=80
    restart: on-failure
    networks:
      - bdic3025j_network
    expose:
      - "80"

  instrument_shop:
    image: echocool/comp3030j_software_engineering_project_musical_instrument_shop:${VERSION:-latest}
    container_name: instrument_shop
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - VIRTUAL_HOST=comp3030j.demo.yuyangwang.org,instrument-shop.demo.yuyangwang.org
      - LETSENCRYPT_HOST=comp3030j.demo.yuyangwang.org,instrument-shop.demo.yuyangwang.org
      - VIRTUAL_PORT=8080
    networks:
      - instrument_shop_network
    expose:
      - "8080"
    restart: on-failure


  bdic3023j-software-methodology-q-a-platform:
    image: echocool/bdic3023j-software-methodology-q-a-platform:${VERSION:-latest}
    container_name: bdic3023j-software-methodology-q-a-platform
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - VIRTUAL_HOST=bdic3023j.demo.yuyangwang.org,qa.demo.yuyangwang.org
      - LETSENCRYPT_HOST=bdic3023j.demo.yuyangwang.org,qa.demo.yuyangwang.org
      - VIRTUAL_PORT=5000
    expose:
      - "5000"
    networks:
      - bdic3023j_network
    restart: on-failure



  comp3019j-web-application-development-grocery-list-website:
    image: echocool/comp3019j-web-application-development-grocery-list-website:${VERSION:-latest}
    container_name: comp3019j-web-application-development-grocery-list-website
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - comp3019j_network
    expose:
      - "5000"
    environment:
      - VIRTUAL_HOST=comp3019j.demo.yuyangwang.org,grocery-list.demo.yuyangwang.org
      - LETSENCRYPT_HOST=comp3019j.demo.yuyangwang.org,grocery-list.demo.yuyangwang.org
      - VIRTUAL_PORT=5000
    restart: on-failure

  # Offer master project
  fyp_offer_master_nginx:
    image: echocool/fyp_offer_master_nginx:${VERSION:-latest}
    container_name: fyp_offer_master_reverse_proxy
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - fyp_offer_master_springboot_admin
      - fyp_offer_master_springboot
      - fyp_offer_master_vue_user
      - fyp_offer_master_vue_admin
      - fyp_offer_master_portainer
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=comp3032j.demo.yuyangwang.org,offer-master.demo.yuyangwang.org
      - LETSENCRYPT_HOST=comp3032j.demo.yuyangwang.org,offer-master.demo.yuyangwang.org
      - VIRTUAL_PORT=80
    networks:
      - offer_master_network
    restart: on-failure

  fyp_offer_master_springboot_admin:
    image: echocool/fyp_offer_master_springboot_admin:${VERSION:-latest}
    container_name: fyp_offer_master_springboot_admin
    deploy:
      resources:
        limits:
          memory: 256M
    expose:
      - "8081"
    networks:
      - offer_master_network
    restart: on-failure

  # springboot backend
  fyp_offer_master_springboot:
    image: echocool/fyp_offer_master_springboot:${VERSION:-latest}
    container_name: fyp_offer_master_springboot
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      fyp_offer_master_db:
        condition: service_healthy
    environment:
      - SERVER_ADDRESS=fyp_offer_master_springboot
      - DB_URL=jdbc:mysql://fyp_offer_master_db:3306/offermaster
      - DB_USERNAME=root
      - DB_PASSWORD=offermaster
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      - DB_PLATFORM=
      - OAUTH_ECHOCOOL_REDIRECT_URL=http://comp3032j.demo.yuyangwang.org/login
    expose:
      - "8080"
    networks:
      - offer_master_network
    restart: on-failure


  # user portal
  fyp_offer_master_vue_user:
    image: echocool/fyp_offer_master_vue_user:${VERSION:-latest}
    container_name: fyp_offer_master_vue_user
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - fyp_offer_master_springboot
    expose:
      - "8080"
    networks:
      - offer_master_network
    restart: on-failure


  # admin portal
  fyp_offer_master_vue_admin:
    image: echocool/fyp_offer_master_vue_admin:${VERSION:-latest}
    container_name: fyp_offer_master_vue_admin
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - fyp_offer_master_springboot
    expose:
      - "8080"
    networks:
      - offer_master_network
    restart: on-failure


  fyp_offer_master_django_ml:
    image: echocool/fyp_offer_master_django_ml:${VERSION:-latest}
    container_name: fyp_offer_master_django_ml
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - fyp_offer_master_springboot
    expose:
      - "8080"
    networks:
      - offer_master_network
    restart: on-failure

  fyp_offer_master_portainer:
    image: portainer/portainer-ce
    privileged: true
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
    expose:
      - "9000"
    ports:
      - "8800:8000"
      - "9900:9000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`ipa-008.ucd.ie`) && PathPrefix(`/portainer`)"
      - "traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/portainer"
      - "traefik.http.routers.whoami.middlewares=portainer-stripprefix@docker"
      - "traefik.http.routers.whoami.entrypoints=web-secure"
      - "traefik.http.routers.whoami.tls=false"
      - "traefik.http.services.whoami.loadbalancer.server.scheme=http"
      - "traefik.http.services.whoami.loadbalancer.server.port=9000"
    networks:
      - offer_master_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - fyp_offer_master_portainer_data_volume:/data


  fyp_offer_master_db:
    image: hsheth2/mysql-low-memory:8.0
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - MYSQL_DATABASE=offermaster
      - MYSQL_ROOT_PASSWORD=offermaster
    expose:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 20
    networks:
      - offer_master_network

  fyp_offer_master_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fyp_offer_master_phpmyadmin
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      PMA_HOST: fyp_offer_master_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: http://ipa-008.ucd.ie/phpmyadmin
    restart: always
    networks:
      - offer_master_network
    ports:
      - "8088:80"

  influxdb:
    container_name: influxdb
    image: influxdb:2.6.1-alpine
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - grafana_network
    environment:
      - VIRTUAL_HOST=influxdb.demo.yuyangwang.org
      - LETSENCRYPT_HOST=influxdb.demo.yuyangwang.org
      - VIRTUAL_PORT=8086
    volumes:
      - influxdb-lib:/var/lib/influxdb2
    env_file:
      # BE SURE TO CHANGE THIS LINE BEFORE GOING TO PRODUCTION
      - ./influx2.env
    expose:
      - "8086"
    restart: always
    privileged: true

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    depends_on:
      - node-exporter
      - nginx-exporter
#      - cadvisor
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - VIRTUAL_HOST=prometheus.demo.yuyangwang.org
      - LETSENCRYPT_HOST=prometheus.demo.yuyangwang.org
      - VIRTUAL_PORT=9090
    networks:
      - grafana_network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.size=512MB'
    expose:
      - "9090"

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:9.4.9
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - grafana_network
    environment:
      - VIRTUAL_HOST=grafana.demo.yuyangwang.org
      - LETSENCRYPT_HOST=grafana.demo.yuyangwang.org
      - VIRTUAL_PORT=3000
    volumes:
      # Note: The 'ro' option specifies that the volume is mounted in read-only mode.
      # However, certain files such as grafana.ini may require write access. Be mindful of security implications when removing ':ro'.
      # Docs : https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3
      - ./grafana/etc:/etc/grafana:ro
      - grafana-lib:/var/lib/grafana
      - grafana-log:/var/log/grafana
    env_file:
      # BE SURE TO CHANGE THIS LINE BEFORE GOING TO PRODUCTION
      - ./grafana.env
    expose:
      - "3000"
    depends_on:
      - influxdb
      - prometheus
    restart: always
    privileged: true

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    expose:
      - "9100"
    networks:
      - grafana_network
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    depends_on:
      - nginx-proxy
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
    command:
      - '-nginx.scrape-uri=http://nginx-proxy:8080/status'
    expose:
      - "9113"
    networks:
      - grafana_network
    restart: always

#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor
#    deploy:
#      mode: global
#      resources:
#        limits:
#          memory: 128M
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#    expose:
#      - "8080"
#    networks:
#      - grafana_network
#    restart: always


volumes:
  fyp_offer_master_db_data_volume:
  fyp_offer_master_portainer_data_volume:
  conf:
  vhost:
  html:
  certs:
  acme:
  influxdb-lib:
  grafana-lib:
  grafana-log:
  prometheus_data:

networks:
  offer_master_network:
  comp3019j_network:
  oath_center_network:
  bdic3023j_network:
  instrument_shop_network:
  bdic3025j_network:
  jupyter_notebook_reader_network:
  maintenance_network:
  grafana_network: