name: Docker-compose build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose --version
      - name: Test with docker-compose
        run: docker-compose config
      - run: docker-compose config -q

